pages:
    image: asciidoctor/docker-asciidoctor
    stage: deploy
    only:
      - main
    script:
      - asciidoctor index.adoc --out-file public/index.html
    artifacts:
      paths:
        - public
